# -*- coding: utf-8 -*-
"""LangChain-Langsmith-integration-Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBDolREsRXig1zkeiRY0cYwusyb9q3P6
"""

#setup environment
#  API key used to authenticate with LangSmith platform
# This allows tracking, debugging, and evaluation of LLM calls

LANGCHAIN_API_KEY="your API Key"

# Project name in LangSmith dashboard
# Helps organize experiments, test runs, and environments (e.g., dev, test, prod)
LANGCHAIN_PROJECT ="TEST LLM APP"

!pip install langchain_groq # Install Groq integration for LangChain
from ast import mod
import os
# Set LangSmith environment variables for tracing & monitoring
os.environ["LANGCHAIN_API_KEY"] = LANGCHAIN_API_KEY  # Auth key for LangSmith
os.environ["LANGCHAIN_PROJECT"] = LANGCHAIN_PROJECT # Project name in dashboard
os.environ["LANGCHAIN_TRACING_V2"]= 'true' # Enable tracing/logging

# Import output parser (converts model output to plain string)
from langchain_core.output_parsers import StrOutputParser
# Import Groq LLM wrapper
from langchain_groq import ChatGroq

# Initialize LLM with Groq API
llm=ChatGroq(
    api_key= "your API key",
    model="llama-3.3-70b-versatile",
    temperature = 0 ,
    max_tokens = None

)
# Output parser to convert response into string format
parser=StrOutputParser()
# Create a simple chain: LLM → Parser
chain= llm | parser
# Invoke the chain with a prompt
response= chain.invoke('tell me about AI in Medical')
# Print the final response
print(response)